server:
  port: 8081

spring:
#允许多个接口使用相同的服务
  main:
    allow-bean-definition-overriding: true
#是否失败重试(true)
  cloud:
    loadbalancer:
      retry:
        enabled: true
#链路跟踪配置
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
#spring更改类程序文件不使用热部署自动重启
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

#是否开启断路器(false)
feign:
  hystrix:
    enabled: true

#断路器超时配置(true)
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      #断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试(>ConnectTimeout+ReadTimeout)
      isolation:
        thread:
          timeoutInMilliseconds: 19000
  #并发执行的最大线程数(10)
  threadpool:
    default:
      coreSize: 500
#负载超时配置
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 15000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  #对当前实例的重试次数
  MaxAutoRetries: 0

